import type { AttackAuditReport, AttackResult } from "./types.js";

export function serializeAttackReport(report: AttackAuditReport): string {
  return JSON.stringify(report, null, 2);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function fmt(value: number | null, digits = 4): string {
  return value === null ? "&mdash;" : value.toFixed(digits);
}

function row(r: AttackResult): string {
  return `      <tr>
        <td><code>${escapeHtml(r.attack)}</code></td>
        <td class="num">${r.driftAfter.toFixed(4)}</td>
        <td class="num">${r.survivalRatio === null ? "&mdash;" : r.survivalRatio.toFixed(2)}</td>
        <td class="num">${fmt(r.psnr, 2)}</td>
        <td class="num">${fmt(r.ssim)}</td>
      </tr>`;
}

/** Render an attack-audit report as a standalone HTML page. */
export function renderAttackHtmlReport(report: AttackAuditReport): string {
  const { driftBefore, results, summary } = report;
  const rows = results.map(row).join("\n");
  const limitations = report.limitations.map((l) => `      <li>${escapeHtml(l)}</li>`).join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>OpenArtShield attack audit</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.5 system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem auto; max-width: 860px; padding: 0 1rem; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .sub { color: #777; margin-top: 0; }
  .meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 0.5rem 1.5rem; margin: 1.25rem 0; }
  .meta div { font-size: 0.9rem; }
  .meta b { display: block; color: #777; font-weight: 600; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.04em; }
  table { border-collapse: collapse; width: 100%; margin-top: 0.5rem; }
  th, td { padding: 0.4rem 0.6rem; border-bottom: 1px solid #8883; text-align: left; }
  th { font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.03em; color: #777; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85em; }
  .note { margin-top: 1.5rem; padding: 0.75rem 1rem; border-left: 3px solid #f0ad4e; background: #f0ad4e1a; font-size: 0.88rem; }
  .note ul { margin: 0.4rem 0 0; padding-left: 1.1rem; }
  footer { margin-top: 2rem; color: #888; font-size: 0.8rem; }
</style>
</head>
<body>
  <h1>OpenArtShield attack audit</h1>
  <p class="sub">Backend: <code>${escapeHtml(report.backend)}</code> &middot; schema v${escapeHtml(report.version)}</p>

  <div class="meta">
    <div><b>Cloak drift (before attacks)</b>${driftBefore.toFixed(4)}</div>
    <div><b>Attacks tested</b>${summary.attacksTested}</div>
    <div><b>Mean survival ratio</b>${summary.meanSurvivalRatio === null ? "&mdash;" : summary.meanSurvivalRatio.toFixed(2)}</div>
    <div><b>Worst-case survival</b>${summary.minSurvivalRatio === null ? "&mdash;" : summary.minSurvivalRatio.toFixed(2)}</div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Attack</th>
        <th class="num">Drift after</th>
        <th class="num">Survival ratio</th>
        <th class="num">PSNR (dB)</th>
        <th class="num">SSIM</th>
      </tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>

  <div class="note">
    <strong>Limitations</strong>
    <ul>
${limitations}
    </ul>
  </div>
  <footer>Generated by OpenArtShield &middot; <code>oas attack</code></footer>
</body>
</html>
`;
}
