import type { AuditReport, AuditResult } from "./types.js";

// Turn an audit report into a standalone HTML page. Pure string work - no IO, no
// DOM - so it stays in core and is trivial to test. Inline CSS keeps the output
// a single self-contained file you can open or commit.

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function fmt(value: number | null, digits = 3): string {
  if (value === null) return "&mdash;";
  return value.toFixed(digits);
}

function resultRow(r: AuditResult): string {
  const ok = r.messageRecovered;
  const cls = ok ? "ok" : "fail";
  const recovered = r.recoveredMessage === null ? "(none)" : escapeHtml(r.recoveredMessage);
  return `      <tr class="${cls}">
        <td><code>${escapeHtml(r.transform)}</code></td>
        <td class="center">${ok ? "yes" : "no"}</td>
        <td class="center">${r.checksumValid ? "yes" : "no"}</td>
        <td class="num">${(r.bitAccuracy * 100).toFixed(1)}%</td>
        <td class="num">${fmt(r.psnr, 2)}</td>
        <td class="num">${fmt(r.ssim, 4)}</td>
        <td>${recovered}</td>
      </tr>`;
}

/** Render an audit report as a single self-contained HTML document. */
export function renderHtmlReport(report: AuditReport): string {
  const { image, watermark, summary, results } = report;
  const rows = results.map(resultRow).join("\n");
  const recoveredPct =
    summary.totalTransforms === 0
      ? 0
      : (summary.successfulRecoveries / summary.totalTransforms) * 100;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>OpenArtShield audit report</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.5 system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem auto; max-width: 900px; padding: 0 1rem; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .sub { color: #777; margin-top: 0; }
  .meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 0.5rem 1.5rem; margin: 1.25rem 0; }
  .meta div { font-size: 0.9rem; }
  .meta b { display: block; color: #777; font-weight: 600; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.04em; }
  table { border-collapse: collapse; width: 100%; margin-top: 0.5rem; }
  th, td { padding: 0.4rem 0.6rem; border-bottom: 1px solid #8883; text-align: left; }
  th { font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.03em; color: #777; }
  td.center, th.center { text-align: center; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  tr.ok td:nth-child(2) { color: #2e7d32; font-weight: 600; }
  tr.fail td:nth-child(2) { color: #c62828; font-weight: 600; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85em; }
  .note { margin-top: 1.5rem; padding: 0.75rem 1rem; border-left: 3px solid #f0ad4e; background: #f0ad4e1a; font-size: 0.88rem; }
  footer { margin-top: 2rem; color: #888; font-size: 0.8rem; }
</style>
</head>
<body>
  <h1>OpenArtShield audit report</h1>
  <p class="sub">Report schema v${escapeHtml(report.version)}</p>

  <div class="meta">
    <div><b>Image</b>${image.path ? escapeHtml(image.path) + " &middot; " : ""}${image.width}&times;${image.height}, ${image.channels} ch</div>
    <div><b>Message</b><code>${escapeHtml(watermark.expectedMessage)}</code></div>
    <div><b>Seed</b>${watermark.seed}</div>
    <div><b>Strength</b>${watermark.strength}</div>
    <div><b>Repetitions</b>${watermark.repetitions}</div>
    <div><b>Recovered</b>${summary.successfulRecoveries} / ${summary.totalTransforms} (${recoveredPct.toFixed(0)}%)</div>
    <div><b>Avg bit accuracy</b>${(summary.averageBitAccuracy * 100).toFixed(1)}%</div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Transform</th>
        <th class="center">Recovered</th>
        <th class="center">Checksum</th>
        <th class="num">Bit acc.</th>
        <th class="num">PSNR (dB)</th>
        <th class="num">SSIM</th>
        <th>Recovered message</th>
      </tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>

  <p class="note">
    A "recovered" row means the embedded signal survived that specific transform
    at these parameters. It does <strong>not</strong> mean the image is protected
    from AI training, copying, or editing. Treat every result as experimental.
  </p>

  <footer>Generated by OpenArtShield &middot; <code>oas audit</code></footer>
</body>
</html>
`;
}
